# Generated by Django 5.2.11 on 2026-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionlog',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
